---
- hosts: vm # 情報を取得したいVMのグループを指定
  gather_facts: false
  tasks:
    - name: get hostname
      ansible.builtin.command:
        cmd: hostname
      register: res_hostname

    - name: copy file #取得した情報をファイルに書き出すためのタスク
      ansible.builtin.copy:
        content: "{{ res_hostname.stdout }}"
        dest: /tmp/{{ inventory_hostname }}.txt
      delegate_to: controller # EEではなくコントローラーに保存するために指定
