---
- hosts: localhost
  connection: local
  tasks:
    - name: get /etc/passwd
      ansible.builtin.command:
        cmd: cat /etc/passwd
      register: res_passwd

    - name: display /etc/passwd
      ansible.builtin.debug:
        var: res_passwd.stdout_lines

- hosts: vm
  tasks:
    - name: copy file
      ansible.builtin.copy:
        content: "{{ res_passwd.stdout }}"
        dest: /tmp/passwd 
